apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data-volume-claim
  labels:
    app: rabbitmq-label
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
