name: Publish packages

on:
  push:
    branches:
      - main

jobs:
  publish-postgres-operator:
    name: Publish Postgres Operator
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install imgpkg
        shell: bash
        run: |
          wget -nv -O- https://github.com/vmware-tanzu/carvel-imgpkg/releases/download/v0.28.0/imgpkg-linux-amd64 > /tmp/imgpkg
          chmod 755 /tmp/imgpkg
      - name: Calculate variables
        run: |
          echo "REPOSITORY_SHA7=${GITHUB_SHA::7}" >>${GITHUB_ENV}
      - name: Build and Publish Postgres Operator
        run: |
          packages/postgres-operator/build.sh
          /tmp/imgpkg push -i ghcr.io/${{github.repository}}/postgres-operator:sha-${REPOSITORY_SHA7} -f packages/postgres-operator --registry-username=${{github.actor}} --registry-password=${{secrets.GITHUB_TOKEN}}
          /tmp/imgpkg push -i ghcr.io/${{github.repository}}/postgres-operator:latest -f packages/postgres-operator --registry-username=${{github.actor}} --registry-password=${{secrets.GITHUB_TOKEN}}