name: Publish packages

on:
  push:
    branches:
      - main

jobs:
  publish-packages:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install imgpkg
        shell: bash
        run: |
          wget -nv -O- https://github.com/vmware-tanzu/carvel-imgpkg/releases/download/v0.28.0/imgpkg-linux-amd64 > /tmp/imgpkg
          chmod 755 /tmp/imgpkg

      - name: Calculate variables
        run: |
          echo "REPOSITORY_SHA7=${GITHUB_SHA::7}" >>${GITHUB_ENV}

      # - name: Build and publish tce-0.11
      #   shell: bash
      #   run: |
      #     packages/tce-0.11/build.sh
      #     /tmp/imgpkg push -i ghcr.io/${{github.repository}}/tce-0.11:sha-${REPOSITORY_SHA7} -f packages/tce-0.11 --registry-username=${{github.actor}} --registry-password=${{secrets.GITHUB_TOKEN}}

      # - name: Build and publish tce-0.12
      #   shell: bash
      #   run: |
      #     packages/tce-0.12/build.sh
      #     /tmp/imgpkg push -i ghcr.io/${{github.repository}}/tce-0.12:sha-${REPOSITORY_SHA7} -f packages/tce-0.12 --registry-username=${{github.actor}} --registry-password=${{secrets.GITHUB_TOKEN}}

      - name: Build and publish gemfire
        shell: bash
        run: |
          packages/gemfire/build.sh
          /tmp/imgpkg push -i ghcr.io/${{github.repository}}/gemfire:sha-${REPOSITORY_SHA7} -f packages/gemfire --registry-username=${{github.actor}} --registry-password=${{secrets.GITHUB_TOKEN}}
